### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by zarcha** [jkbenaim/psp2master#1]
I can not seem to build this. i constantly get errors. can you either upload a release or give step by step instructions to build it?

**Comment by jkbenaim** [comment]
https://github.com/jkbenaim/psp2master/releases/tag/v1.1
Sorry about that. I somehow set this release as a draft instead of publishing it. Let me know if it works for you.

**Comment by zarcha** [comment]
Wonderful, i was easily able to create a master disc and use it on my dev kit. Thank you.
